### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by phcent** [element-plus/element-plus-nuxt-starter#2]
``SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:984:16)
    at Module._compile (internal/modules/cjs/loader.js:1032:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async __instantiateModule__ (file:///D:/web/web/.nuxt/dist/server/server.mjs:2432:3)
(node:33632) UnhandledPromiseRejectionWarning: D:\web\web\node_modules\element-plus\es\index.js:1
import installer from './defaults';

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus-nuxt-starter/issues/1#issuecomment-942931015
