### ISSUE TITLE
运行不起来

### ISSUE THREAD

**Issue by shuiche-it** [element-plus/element-plus-nuxt-starter#21]
```
$ nuxi dev
Nuxt CLI v3.0.0-27365509.a2e2e04                                                                                                12:35:26
                                                                                                                                12:35:26
  > Local:    http://localhost:3000/ 
  > Network:  http://10.0.0.15:3000/

12:35:28 PM [vite] changed tsconfig file detected: /Users/zhangzexuan/Desktop/element-plus-nuxt-starter-main/.nuxt/tsconfig.json - Clearing cache and forcing full-reload to ensure typescript is compiled with updated config values.
12:35:28 PM [vite] changed tsconfig file detected: /Users/zhangzexuan/Desktop/element-plus-nuxt-starter-main/.nuxt/tsconfig.json - Clearing cache and forcing full-reload to ensure typescript is compiled with updated config values.
12:35:28 PM [vite] changed tsconfig file detected: /Users/zhangzexuan/Desktop/element-plus-nuxt-starter-main/.nuxt/tsconfig.json - Clearing cache and forcing full-reload to ensure typescript is compiled with updated config values.
12:35:28 PM [vite] changed tsconfig file detected: /Users/zhangzexuan/Desktop/element-plus-nuxt-starter-main/.nuxt/tsconfig.json - Clearing cache and forcing full-reload to ensure typescript is compiled with updated config values.
ℹ Vite warmed up in 903ms                                                                                                       12:35:28
✔ Vite server built in 3726ms                                                                                                   12:35:31
✔ Nitro built in 235 ms                                                                                                         12:35:31
exports is not defined
  at $id_e75fe73f (file://./.nuxt/dist/server/server.mjs:1083:10)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:3337:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:3284:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:3309:13)  
  at $id_cbe5172d (file://./.nuxt/dist/server/server.mjs:998:37)  
  at __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:3337:9)  
  at __ssrLoadModule__ (file://./.nuxt/dist/server/server.mjs:3284:25)  
  at ssrImport (file://./.nuxt/dist/server/server.mjs:3309:13)  
  at $id_a031119c (file://./.nuxt/dist/server/server.mjs:938:37)  
  at async __instantiateModule__ (file://./.nuxt/dist/server/server.mjs:3337:3)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)
m.default is not a function
  at file://./.nuxt/dist/server/server.mjs:10:126  
  at processTicksAndRejections (internal/process/task_queues.js:95:5)  
  at async renderToString (file://./node_modules/vue-bundle-renderer/dist/index.mjs:247:19)  
  at async renderMiddleware (file://./.nuxt/nitro/index.mjs:191:20)  
  at async handle (file://./node_modules/h3/dist/index.mjs:601:19)


```

**Comment by xiaoxian521** [comment]
The problem is from nuxt, it has been fixed
https://github.com/nuxt/framework/issues/2679
