### ISSUE TITLE
Error Starting 

### ISSUE THREAD

**Issue by ElBinko** [element-plus/element-plus-nuxt-starter#24]
Hello,

Using the latest version of this repository, after git clone, yarn install and yarn run dev, when you you access the localhost:3000 the following error is printed in the console: 

> [Vue warn]: Unhandled error during execution of watcher callback 
>   at <ElPopperTrigger id="el-id-5038-0" virtual-ref=undefined open=false  ... >
> 
>  ERROR  [worker] Element is not defined                                                                   
> 
>   at isElement$1 (node_modules/element-plus/dist/index.full.js:2144:43)
>   at vue.watch.immediate (node_modules/element-plus/dist/index.full.js:7453:13)
>   at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
>   at callWithAsyncErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:166:21)
>   at doWatch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1744:13)
>   at Object.watch (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1656:12)
>   at setup (node_modules/element-plus/dist/index.full.js:7452:11)
>   at callWithErrorHandling (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:157:22)
>   at setupStatefulComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6977:29)
>   at setupComponent (node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6933:11)
> 
> 
>  ERROR  [proxy] connect ENOENT /var/folders/sw/sbmrkj352zb87qyhrv3c22jh0000gn/T/nitro/worker-1474-1.sock     
>

**Comment by xiaoxian521** [comment]
Please provide node version

**Comment by ElBinko** [comment]
16.14.0

**Comment by linjiejim** [comment]
Same here with node version `v16.13.1`. 

![Screen Shot 2022-03-09 at 5 13 52 PM](https://user-images.githubusercontent.com/18286145/157410262-a3be2589-9f61-40e1-8197-ad401e99afee.png)

**Comment by geongeorge** [comment]
Same issue here with node 16.11.0
